# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: QQ阅读APP

on:
  workflow_dispatch:
  schedule:
     - cron: '0 1 * * *'
  watch:
    types: started
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
        QQ_QQreadURL: ${{ secrets.QQ_QQreadURL }}
    steps:
      - name: Checkout
        run: |
          git clone https://github.com/ziye66666/JavaScript.git ~/JavaScript
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        if: env.QQ_QQreadURL
        run: |
          cd ~/JavaScript
          npm install
      - name: '运行 【QQ阅读APP】'
        if: env.QQ_QQreadURL
        run: |
          cd ~/JavaScript
          node Task/QQread.js
        env:
          QQ_QQreadURL: ${{ secrets.QQ_QQreadURL }}