name: 书旗小说‍📕

on:
    workflow_dispatch:
    schedule:
        - cron: "7 0-23 * * *"
    watch:
        types: [started]
jobs:
    build:
        runs-on: ubuntu-latest
        if: github.event.repository.owner.id == github.event.sender.id
        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js 10.x
              uses: actions/setup-node@v1
              with:
                  node-version: 10.x
            - name: npm install
              run: |
                  npm install
            - name: '运行 【书旗小说‍📕‍】'
              run: |
                  node onlyOneExecute.js
              env:
                  SQ_shuqiuserURL: ${{ secrets.SQ_shuqiuserURL }}
                  SQ_shuqicjBODY: ${{ secrets.SQ_shuqicjBODY }}
                  SQ_shuqicjyURL: ${{ secrets.SQ_shuqicjyURL }}
                  SQ_shuqijlbody: ${{ secrets.SQ_shuqijlbody }}
                  SQ_shuqijsqdBODY: ${{ secrets.SQ_shuqijsqdBODY }}
                  SQ_shuqijsydBODY: ${{ secrets.SQ_shuqijsydBODY }}
                  SQ_shuqijsyURL: ${{ secrets.SQ_shuqijsyURL }}		
                  SQ_shuqiqdBODY: ${{ secrets.SQ_shuqiqdBODY }}
                  SQ_shuqisyBODY: ${{ secrets.SQ_shuqisyBODY }}
                  SQ_shuqispBODY: ${{ secrets.SQ_shuqispBODY }}
                  TG_BOT_TOKEN: ${{ github.event.client_payload.TG_BOT_TOKEN2 || secrets.TG_BOT_TOKEN2 }}
                  TG_USER_ID: ${{ github.event.client_payload.TG_USER_ID2 || secrets.TG_USER_ID2 }}
                  SYNCURL: https://github.com/jackpater/App_auto/raw/ziye/Task/shuqi.js
