# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: 什么值得买签到⏰

on:
  workflow_dispatch:
  schedule:
     - cron: '0 1 * * *'
  watch:
    types: started
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
        SMZDM_COOKIE: ${{ secrets.SMZDM_COOKIE }}
    steps:
      - name: Checkout
        run: |
          git clone https://github.com/fashionzzZ/sign-actions.git ~/sign-actions
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        if: env.SMZDM_COOKIE
        run: |
          cd ~/sign-actions
          npm install
      - name: '运行 【什么值得买签到⏰】'
        if: env.SMZDM_COOKIE
        run: |
          cd ~/sign-actions
          node smzdm.js
        env:
          TG_API: ${{ secrets.TG_API }}
          SMZDM_COOKIE: ${{ secrets.SMZDM_COOKIE }}