name: 微博签到打卡⏰

on:
  workflow_dispatch:
  schedule:
     - cron: '3 0 * * *'
  watch:
    types: started
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
        WB_TOKEN: ${{ secrets.WB_TOKEN }}
        WB_PAY: ${{ secrets.WB_PAY }}
    steps:
      - name: Checkout
        run: |
          git clone https://github.com/jackpater/App_auto.git ~/App_auto
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        if: env.WB_TOKEN
        run: |
          cd ~/App_auto
          npm install
      - name: '运行 【新浪微博⏰】'
        if: env.WB_TOKEN
        run: |
          cd ~/App_auto
          node weibo.js
        env:
          TZ: Asia/shanghai
          WB_TOKEN: ${{ secrets.WB_TOKEN }}
          WB_PAY: ${{ secrets.WB_PAY }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN2 }}
          TG_USER_ID: ${{ secrets.TG_USER_ID2 }}