name: 微博签到‍

on:
    workflow_dispatch:
    schedule:
        - cron: "5 0 * * *"
    watch:
        types: [started]
jobs:
    build:
        runs-on: ubuntu-latest
        if: github.event.repository.owner.id == github.event.sender.id
        steps:
            - uses: actions/checkout@v1
            - uses: actions/checkout@v1
            - name: Use Node.js 10.x
              uses: actions/setup-node@v1
              with:
                  node-version: 10.x
            - name: npm install
              run: |
                  npm install
            - name: '运行 【微博签到‍】'
              run: |
                  node onlyOneExecute.js
              env:
                  TG_BOT_TOKEN: ${{ github.event.client_payload.TG_BOT_TOKEN || secrets.TG_BOT_TOKEN }}
                  TG_USER_ID: ${{ github.event.client_payload.TG_USER_ID || secrets.TG_USER_ID }}
                  WB_TOKEN: ${{ github.event.client_payload.secrets.WB_TOKEN || secrets.WB_TOKEN }}
                  WB_PAY: ${{ github.event.client_payload.secrets.WB_PAY || secrets.WB_PAY }}
                  SYNCURL: https://github.com/jackpater/TaskAction/raw/master/workflow/weibo.js
