name: 滴滴出行

on:
    workflow_dispatch:
    schedule:
        - cron: "0 12,17 * * *"
    watch:
        types: [started]
jobs:
    build:
        runs-on: ubuntu-latest
        if: github.event.repository.owner.id == github.event.sender.id
        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js 10.x
              uses: actions/setup-node@v1
              with:
                  node-version: 10.x
            - name: npm install
              run: |
                  npm install
            - name: '运行 【滴滴出行】'
              run: |
                  node onlyOneExecute.js
              env:
                  TG_BOT_TOKEN: ${{ github.event.client_payload.TG_BOT_TOKEN2 || secrets.TG_BOT_TOKEN2 }}
                  TG_USER_ID: ${{ github.event.client_payload.TG_USER_ID2 || secrets.TG_USER_ID2 }}
                  DIDI_CITY: ${{ secrets.DIDI_CITY}}
                  DIDI_TOKEN: ${{ secrets.DIDI_TOKEN }}
                  SYNCURL: https://github.com/zZPiglet/Task/raw/master/DiDi/DiDi.js