name: 笑谱

on:
    workflow_dispatch:
    # 测试
    schedule:
        - cron: "*/10 * * * *"
    watch:
        types: [started]
jobs:
    build:
        runs-on: ubuntu-latest
        if: github.event.repository.owner.id == github.event.sender.id
        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js 12.x
              uses: actions/setup-node@v1
              with:
                  node-version: 12.x
            - name: npm install
              run: |
                  npm install
            - name: '运行 【笑谱】'
              run: |
                  node onlyOneExecute.js
              env:
                  TG_BOT_TOKEN: ${{ github.event.client_payload.TG_BOT_TOKEN || secrets.TG_BOT_TOKEN }}
                  TG_USER_ID: ${{ github.event.client_payload.TG_USER_ID || secrets.TG_USER_ID }}
                  hostname: ${{ secrets.hostname }}
                  XP_iboxpayHEADER: ${{ secrets.XP_iboxpayHEADER }}
                  XP_XrefreshTOKEN: ${{ secrets.XP_refreshTOKEN }}
                  SYNCURL: https://github.com/ziye12/JavaScript/raw/main/Task/iboxpay.js
